name: Build Repository

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * *"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Swap
        shell: bash
        run: |
            export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
            sudo swapoff $SWAP_FILE
            sudo rm $SWAP_FILE
            sudo fallocate -l 8G $SWAP_FILE
            sudo chmod 600 $SWAP_FILE
            sudo mkswap $SWAP_FILE
            sudo swapon $SWAP_FILE
    
      - run: git config --global user.email "ci@fuchss.org" && git config --global user.name "GitHub CI"
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Remove last build (iff any)
        run: sudo rm -rf element-android
        
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: "fdroid"
          path: "fdroid"
      
      - name: Init Repository Secrets
        run: |
          echo $JAVA_SIGNING_KEY_ANDROID | base64 --decode > apps.jks
          echo $KEYSTORE_FILE | base64 --decode > fdroid/keystore.p12
        env:
          JAVA_SIGNING_KEY_ANDROID: ${{ secrets.JAVA_SIGNING_KEY_ANDROID }}
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      
      - name: Build Element.io
        run: bash scripts/element.io.sh
      
      - name: Check if there are changes
        id: changes
        run: echo "changed=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT
        
      - run: git add releases && git commit -m "Update from $GITHUB_SHA" && git push origin main
        if: steps.changes.outputs.changed != 0
      - run: cd fdroid && git add . && git commit -m "Update from $GITHUB_SHA" && git checkout --orphan fdroid-stage && git commit -m "Update from $GITHUB_SHA" && git push origin fdroid-stage:fdroid -f
        if: steps.changes.outputs.changed != 0
