name: Build Repository

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "00 */6 * * *"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: git config --global user.email "ci@fuchss.org" && git config --global user.name "GitHub CI"
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Remove last build (iff any)
        run: sudo rm -rf element-android
        
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: "fdroid"
          path: "fdroid"
      
      - name: Init Repository Secrets
        run: |
          echo $JAVA_SIGNING_KEY_ANDROID | base64 --decode > apps.jks
          echo $KEYSTORE_FILE | base64 --decode > fdroid/keystore.p12
        env:
          JAVA_SIGNING_KEY_ANDROID: ${{ secrets.JAVA_SIGNING_KEY_ANDROID }}
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
      
      - name: Build Element.io
        run: bash scripts/element.io.sh
      
      - name: Check if there are changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
        id: changes
        
      - run: git add releases && git commit -m "Update from $GITHUB_SHA" && git push origin main
        if: steps.changes.outputs.changed == 1
      - run: cd fdroid && git add . && git commit -m "Update from $GITHUB_SHA" && git push origin fdroid
        if: steps.changes.outputs.changed == 1
